= Лабораторні роботи з курсу Веб-технології (HTML, CSS)
:toc:
:toc-title: Теми:
:sectnums:

== Git та GitHub. Linux, Command Line.

Мета: Ознайомитись з основними концепціями та інструментами систем контролю версій Git та платформи GitHub, а також навчитися ефективно використовувати їх для керування кодом та спільної розробки.

== Знайомство з мовою HTML.

Мета: ознайомитися з основами мови HTML, вивчити структуру HTML-документа, навчитися використовувати парні та непарні теги для створення початкової розмітки веб-сторінки, а також налаштувати та використовувати інтегроване середовище розробки (IDE) для роботи з HTML-кодом

== Основні теги HTML.

Мета: ознайомитися з основними тегами мови розмітки HTML та навчитися застосовувати їх для створення структурованих html-сторінок.
Використання базових тегів для форматування тексту, створення гіперпосилань, списків, таблиць, зображень та форм.
Реалізація семантичної розмітки для поліпшення доступності та SEO-оптимізації веб-ресурсів.

== CSS властивості шрифту та тексту. Застосування селекторів.

Мета: вивчити основні властивості CSS, пов'язані з форматуванням шрифтів і тексту, а також навчитися застосовувати різні типи CSS-селекторів для створення стилізованих веб-сторінок.

== CSS властивості блоків та фону (padding, margin, display, background).

Мета: ознайомитися з основними CSS властивостями для управління відступами, розташуванням блоків і налаштуванням фону, зокрема з властивостями padding, margin, display та background.
Навчитися застосовувати ці властивості для коректного оформлення та структурування веб-сторінок.

== CSS властивості оформлення блоків (border, box-shadow). «Плаваюча» модель для розміщення зображень й інших елементів.

Мета: ознайомитися з основними CSS властивостями для оформлення блоків, такими як border та box-shadow, а також вивчити «плаваючу» модель для розміщення зображень і інших елементів за допомогою властивості float.
Навчитися використовувати ці властивості для створення візуально привабливих та функціональних веб-сторінок

== CSS позиціонування. CSS псевдокласи та псевдоелементи.

Мета: ознайомитися з принципами CSS позиціонування елементів та навчитися застосовувати псевдокласи і псевдоелементи для покращення інтерфейсу веб-сторінки.
Опанувати використання таких властивостей позиціонування, як static, relative, absolute, fixed, sticky, а також дізнатися про можливості псевдокласів (:hover, :focus, тощо) і псевдоелементів (::before, ::after) для створення інтерактивних та динамічних елементів.

== Робота з Flexbox в CSS. Основи адаптивної верстки: використання media-запитів.

Мета: ознайомитися з принципами роботи Flexbox та основами адаптивної верстки веб-сторінок за допомогою CSS media-запитів.
Навчитися використовувати Flexbox для вирівнювання елементів у контейнерах та media-запити для створення інтерфейсів, які автоматично підлаштовуються під різні розміри екранів і пристроїв, забезпечуючи зручність перегляду та взаємодії з контентом на мобільних, планшетних та десктопних пристроях.

== Основи Grid Layout

Мета: ознайомитися з принципами роботи Grid Layout у CSS для створення гнучких і структурованих макетів веб-сторінок.
Навчитися використовувати Grid Layout для створення складніших багатовимірних сіток.

== Препроцесор (шаблонізатор) Pug, препроцесор SCSS/SASS. Автоматизація процесів верстки.

Мета: ознайомитися з основами роботи препроцесорів Pug та SCSS/SASS для оптимізації процесу верстки веб-сторінок, а також вивчити інструменти автоматизації процесів верстки (Gulp, Webpack, Vite).
Навчитися використовувати препроцесори для спрощення та пришвидшення написання HTML і CSS, а також автоматизувати рутинні завдання для підвищення ефективності розробки.
