= ЛАБОРАТОРНА РОБОТА №6

*Тема: Маніпуляція вебсторінкою за допомогою JavaScript*

*Мета:* метою цієї лабораторної роботи є розробка інтерактивної вебсторінки за допомогою JavaScript, яка буде взаємодіяти з користувачем та змінювати вміст, стилі та властивості різних елементів сторінки залежно від дій користувача.

== Вимоги та самостійна робота:

** Ознайомитися з https://uk.javascript.info/document[роботою з DOM за допомогою JavaScript]
** https://dou.ua/forums/topic/52856[Functions, functions are everywhere: 8 принципів функціонального програмування на прикладах з JavaScript]
** https://javascript.org.ua/shho-take-chysta-funkcziya-pure-function-v-javascript/[Що таке чиста функція (pure function) в javascript?]
** https://www.w3schools.com/HOWTO/howto_js_snackbar.asp[How TO - Snackbar/Toast]
** https://www.w3schools.com/HOWTO/howto_css_modals.asp[How TO - CSS/JS Modal]

== Практична частина

=== Завдання 1

Створіть вебсторінку, яка буде відображати список товарів.

Кожен товар представлений як елемент списку (картка товару) з наступною інформацією:

. id товару: текстовий вузол.
. Назва товару: текстовий вузол.
. Ціна товару: текстовий вузол з відповідною валютою.
. Категорія товару: текстовий вузол.
. Зображення товару: вузол <img> з властивістю src, яка вказує на зображення товару та атрибутом alt (помістити назву товару).
. Кнопка для видалення товару.
. Кнопка для редагування товару.

Ваше завдання полягає в тому, щоб виконати наступні дії за допомогою JavaScript:

. Додавання нового товару:
* Якщо список товарів пустий, відображати текст "Наразі список товарів пустий.
Додайте новий товар."
* Під списком товарів, повинна відображатись кнопка "Додати новий товар", клік по якій, відкриває модальне вікно для внесення інформації про товар.
* Внесення інформації про товар, повинно відбуватись з використанням модального вікна.
* Створити новий елемент (картку товару) списку з інформацією про товар.
* Додати цей елемент (картку товару) до списку товарів.

. Видалення товару:
* При кліці на кнопку "Видалити" у картці товару, цей товар повинен бути видалений зі списку.
* Після видалення товару, вивести Snackbar/Toast в правому куті екрану, з текстом про успішне видалення товару зі списку.

. Редагування інформації про товар:
* При кліці на кнопку редагування товару, відобразити модальне вікно, де можна редагувати цю інформацію.
* Після підтвердження змін, відобразити нову інформацію на сторінці у картці товару.
* Після успішної зміни, вивести Snackbar/Toast в правому куті екрану, з текстом про успішне оновлення інформації товару (відобразити id товару та назву товару).

. Підрахунок загальної вартості товарів:
* Відобразити загальну вартість всіх товарів у відповідному елементі (елемент може бути розміщений у header, aside).

. Фільтрація товарів
* Відобразити блок фільтр товарів у вигляді ряду кнопок з назвами категорій товарів.
* Клік по кнопці виконує фільтр товарів по відповідній категорії.
* Додайте кнопку для скидання фільтрації товарів.

. Сортування товарів
* Відобразити блок з сортуванням товарів у вигляді ряду кнопок: "Сортувати за ціною", "Сортувати за датою створення", "Сортувати за датою оновлення".
* Клік по кнопці виконує відповідне сортування товарів.
* Додайте кнопку для скидання сортування товарів.

. Вимоги до завдання:
* Використовуйте функціональний стиль програмування.
* Використовуйте тільки pure functions.
* Має бути мінімум 3 категорії товару.
* Валідація полів вводу (HTML5-валідація).
* Забезпечте CSS анімацію для додавання/видалення товарів.
* Використовуйте CSS для стилізації відображення товарів і модальних вікон.
* Використання css фреймворків - заборонено!
* Використання alert, confirm, prompt - заборонено!
* Зробіть вашу сторінку адаптивною.
* Валідний та семантичний HTML-код.

=== Завдання 2

Створіть вебсторінку, яка буде відображати простий список завдань (to-do list) з можливістю додавання, редагування, видалення та відзначення завдань як виконаних.

Ваша програма повинна мати такий функціонал:

. Додавання завдань:
* Користувач може вводити нові завдання у текстове поле та додавати їх у список.

. Видалення завдань:
* Кожен елемент списку має кнопку "Видалити", яка дозволяє видаляти завдання.

. Редагування завдань:
* Забезпечте можливість редагування тексту завдань безпосередньо в списку

. Відзначення завдань як виконані:
* Користувач може клікнути на завдання, щоб відзначити його як виконане.
* Відзначені завдання можуть відображатися інакше, наприклад, зі стрічкою чи іншим маркуванням тощо.

. Сортування завдань:
* Додайте можливість сортувати завдання за різними критеріями, за датою додавання, за станом виконання, за датою оновлення.

. Вимоги до завдання:
* Використовуйте функціональний стиль програмування.
* Використовуйте тільки pure functions.
* Валідація полів вводу (HTML5-валідація).
* Стилізуйте ваш список за допомогою CSS, зробіть його привабливим та зручним для користувача.
* Застосуйте анімаційні ефекти, наприклад, під час додавання або видалення елементів списку.
* Зробіть вашу сторінку адаптивною.
* Валідний та семантичний HTML-код.

== Контрольні запитання:

. Що таке DOM, і як він відрізняється від HTML?
. Які методи доступу до елементів DOM в JavaScript ви знаєте?
. Що таке вузол (node) в DOM?
. Які методи пошуку елементів в DOM ви знаєте, і що вони роблять?
. Як можна змінювати вміст елементів DOM за допомогою JavaScript?
. Як можна додавати атрибути до елементів DOM за допомогою JavaScript?
. Як ви можете змінити стилі елементів DOM за допомогою JavaScript?
. Які способи існують для додавання та видалення класів у елементів DOM?
. Що таке event throttling і як вона використовується для оптимізації роботи з подіями в DOM?
