= Правила іменування файлів

== 1. Тільки латинські літери та цифри

Під час вибору назв для файлів використовуйте лише латинські літери, цифри, символи «-» та «_».

Через те, що для української мови існує безліч різних кодувань, багато програм можуть некоректно працювати з файлами, що мають кириличні символи в назві.

При використанні українських символів у назві можуть виникнути такі проблеми:

* Файл коректно відображається під час перегляду через FTP-клієнт, але не відкривається на сайті;
* Ім'я файлу може «побитися» (стати нечитабельним) під час завантаження з локального комп'ютера на сервер або копіювання файлу з сервера на сервер;
* Файл неправильно індексується пошуковими системами;
* Файл не відкривається на комп'ютері користувача тощо.

Добре::

[source,HTML]
bank-statement.pdf

Погано::

[source,HTML]
квитанція(банк).pdf

== 2. Тільки малі літери

Використовуйте лише малі літери для назв файлів.
У Windows назва «Новий Документ.docx» означає те саме, що й «новий документ.docx», але це стосується не всіх операційних систем.
Наприклад, деякі Unix-системи виявляють чутливість до регістру.

Добре::

[source,HTML]
http://cakes.com/popular.html

Погано::

[source,HTML]
http://cakes.com/THEBEST.html

== 3. Не використовуйте пробіл

Якщо назва файлу складається більше, ніж з одного слова, ніколи не використовуйте пробіл для відокремлення слів.
Використовуйте як роздільник символ «-» або «_».

При використанні пробілів посилання на файли можуть бути відмінними від тих, що їх вводить користувач.
Наприклад, назва сторінки about company.html може бути записана як about%20company.html.
Вводячи посилання на sitename.ua/about company.html, користувач не потрапить на потрібну сторінку.

Добре::

[source,HTML]
icon-skype.png

Погано::

[source,HTML]
image 1.jpg

== 4. Осмислені назви англійською мовою

Вказуйте для файлів осмислені назви англійською мовою, уникайте назв «за замовчуванням» (Нова тека 2) та використання трансліту.

Коли користувач збирається перейти за посиланням, він часто звертає увагу на її адресу.
Якщо ім'я сторінки або файлу описує вміст, користувач охоче перейде за посиланням.

Пошукові системи також враховують назву файлу.
Посилання на ваш сайт, що містить у назві ключове слово, дає пошуковим системам зрозуміти, про що ваша сторінка.

Добре::

[source,HTML]
<a href="/authors/shevchenko/biography.html">Біографія Т.Г. Шевченко</a>

Погано::

[source,HTML]
<a href="/section1/folder/storinka-katalogy.html">Каталог товарів</a>


